resolver: lts-3.9

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [ snap-loader-dynamic-0.10.0.3
            , snap-loader-static-0.9.0.2
            , snaplet-postgresql-simple-0.6.0.4
            , resource-pool-catchio-0.2.1.0
            ]

# Override default flag values for local packages and extra-deps
flags: {
    snap-api-tutorial: {development: true},
}
